version: "3.5"

services:
    fpoapp:
      build:
        context: ./
        dockerfile: Dockerfile
      container_name: core
      ports:
        - 80:80
        - 8085:80
      volumes:
        - .:/code
